server:
  port: 8101
spring:
  datasource:
    dynamic:
      hikari:
        connection-timeout: 30000
        max-lifetime: 1800000
        max-pool-size: 15
        min-idle: 5
        connection-test-query: select 1
        pool-name: FebsHikariCP
      primary: base
      datasource:
        base:
          username: akali001
          password: 199048lemon
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://154.89.4.116:3306/akali001?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  boot:
    admin:
      client:
        url: http://${febs-admin}:8401
        username: febs
        password: 123456
        instance:
          prefer-ip: true

  redis:
    database: 0
    host: 116.62.174.104
    port: 6379
    lettuce:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 5000
    password: 7c4a8d09ik0g4
mybatis-plus:
  type-aliases-package: cc.mrbird.febs.common.core.entity.system
  mapper-locations: classpath:mapper/*.xml
  configuration:
    jdbc-type-for-null: null
  global-config:
    banner: false
info:
  app:
    name: ${spring.application.name}
    description: "@project.description@"
    version: "@project.version@"

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

justauth:
  enabled: true
  type:
    github:
      client-id:
      client-secret:
      redirect-uri:
    gitee:
      client-id:
      client-secret:
      redirect-uri:
    tencent_cloud:
      client-id:
      client-secret:
      redirect-uri:
    dingtalk:
      client-id:
      client-secret:
      redirect-uri:
    qq:
      client-id:
      client-secret:
      redirect-uri:
    microsoft:
      client-id:
      client-secret:
      redirect-uri:
  cache:
    type: redis
    prefix: 'FEBS::CLOUD::SOCIAL::STATE::'
    timeout: 1h

febs:
  frontUrl: 'http://localhost:9527'
  doc:
    enable: true
    title: ${spring.application.name}文档
    base-package: cc.mrbird.febs.auth.controller
    description: ${febs.doc.title}
    name: MrBird
    email: 852252810@qq.com
    url: https://mrbird.cc
    version: 2.2-RELEASE
  cloud:
    security:
      enable: true
      only-fetch-by-gateway: false
      anon-uris: /actuator/**,/captcha,/social/**,/v2/api-docs,/v2/api-docs-ext,/login,/resource/**